---
title: "OB_DisEco_Fall2025"
author: "Olivia Burgess"
format: html
editor: visual
---

## 8/29/25

Quarto is a powerful tool for creating dynamic documents that combine text, code, and data visualizations. For your assignments and worksheets, using Quarto will allow you to seamlessly integrate your analysis with your written explanations/comments, making your reports more cohesive and professional.

```{r}
# Function to calculate the area of a circle
area_of_circle <- function(radius) {
  area <- pi * radius^2
  return(area)
}
radius <- 5 # from the example
circle_area <- area_of_circle(radius)
cat("The area of the circle with radius", radius, "is", circle_area, "\n")
```

![This image captures the three corners of the epidemiological triad.is a model for researching health issues, particularly infectious diseases, by examining how th external conditions that either promote or prevent the spread of disease, the pathogen that causes the disease, and the organism that becomes infected. All three elements need to be present and interconnected for a disease to manifest.](images/EpiTriad.png){fig-align="center"}

test corrections

4.  a\. 0.125 days\^-1 1/8

    b\. 2(7)=14 1/14= 0.0714 days \^-1

    c.Rnot=beta/y

    beta=Rnot/y

    15(0.125)=1.875 days \^-1 measles

    17(0.0714) = 1.2138 days\^-1 Rotavirus

    d\. Reff=Rnot(s)

    s=1-0.8=0.2

    15(0.30)=2


7.  The infection was caused by Pasteurella multocida because although it is harmless in antelopes' respiratory tracts it became virulent due to tempurature and humidity which caused hemorrhagic septicemia. To prevent this in the future, disease surveillance can be implemented to monitor the health of species and environment and vaccination protocols and manage the habitat to ensure it is diverse and healthy to promote a strong immune system within animals

10/23/25

Middle East respiratory syndrome coronavirus (MERS-CoV) is mostly found in camels\
(dromedaries), and direct physical contact with camels can lead to transmission to\
humans. Limited human-to-human transmission can occur after close contact and has\
resulted in health care–associated outbreaks. Human MERS-CoV infection can cause\
severe respiratory illness; approximately 35% of reported MERS cases have died.\
Distribution of confirmed cases of MERS by place of infection and month of onset, April\
2012 – September 2025 (European Centre for Disease Prevention and Control)

**Which of the following statements about MERS-CoV are correct? (If it is incorrect,\
provide an explanation why the statement is incorrect.)**

\
1. MERS-CoV is primarily maintained in human populations. 

False. Although camels are the main reservoir host species for MERS-CoV, humans can contract the virus and spread it to other vulnerable people.

2. Camels serve as the main animal reservoir for MERS-CoV. 

True. MERS-CoV is a coronavirus that primarily infects camels in the Middle East, but it can also infect people.

3. Humans are dead-end hosts for MERS-CoV. 

False.mAlthough the virus can only finish brief infection chains, MERS-CoV can infect humans.  Although the disease can infiltrate the target population, it is unable to endure.

4. The estimated case fatality rate for human MERS-CoV infections is approximately\
65%. 

False. Only about 35% of human MERS infections have resulted in death, despite the case fatality rate for MERS-CoV may be greater due to underreporting or other factors.

5. The epidemic curve indicates this is a point source outbreak.

False. A point source outbreak would be indicated by a single peak on the epidemic curve, showing an inflow of cases brought on by a single exposure event. However, following the initial exposure or influx of cases, the number of cases would gradually decline.  Although there is a noticeable decline in occurrences in this epidemic curve after 2020, we can observe a propagating source here where animals are infecting people and some humans are infecting other humans.


1. This Marburg virus outbreak is an emerging infectious disease.  With accidental contact with the reservoir bats, the between-species transfer is .  Nonetheless, there is a comparatively high rate of within-species transmission among healthcare personnel or other individuals in exposed environments.  According to the community epidemiology paradigm created by Fenton and Pedersen, this dynamic fulfills the definition of a possible developing infectious illness.  The outbreak is not only spillover due to human-to-human transmission.  Humans are typically a dead end host in a spillover occurrence because the disease cannot persist for an extended period of time outside of the reservoir host species.

2. Isolation must be required for known Marburg cases.  For extremely likely suspected instances, seclusion may also be necessary.  Isolation does increase the danger of exposure and infection for medical staff and maybe other patients at connected facilities.  Strict personal protective equipment (PPE) regulations, negative pressure rooming, and disinfection and sterilization standards can all help reduce this exposure and infection.  Safe waste management, safe burial and body management, and caving certification or limits are some further concurrent risk-reduction strategies.

11/9/25 (#6)

Pond 1
Prevalence 30.0%
95% CI: lower 14.0%, upper 52.5%

Pond 2
Prevalence: 6.7%
95% CI: lower 0.3%, upper 30.2%

p-value: 0.1987
The prevalence values are not statistically significant at a p-value of 0.1987 because it is greater than 0.05.


Nipah virus ecology varies across regions, resulting in distinct patterns of transmission in places like Malaysia and Bangladesh. Describe how the modes of transmission differ between these two regions and explain how these differences influence the preventive measures recommended in each setting. (8 points)

The ecology of the Nipah virus differs throughout South and Southeast Asia. Pig bridge hosts are the primary means of transmission for the Nipah virus. Humans primarily contract the Nipah virus from infected pigs, whereas pigs can contract it via bats or fruit tainted with bat excrement. Both of these occur within Malaysia. However tainted date palm sap frequently infects people with the Nipah virus in Bangladesh. Bat excrement will contaminate the buckets used to gather sap, and eating raw sap can infect people. Since contact with infected pigs accounts for the majority of cases in Malaysia, early detection and surveillance of the disease is an important preventative approach given the observed mode of transmission. Because pigs are not involved, prevention in Bangladesh focuses on community-level exposure reduction and infection control, preventing bat contamination of date palm sap, and promoting safe caregiving practices in households and health facilities.

Avian reoviruses (ARV) can be transmitted through multiple routes. Describe the different transmission routes of ARV and explain which environmental factors favor its transmission. What pathogen characteristics support one of these transmission routes? Finally, provide an example of a wild bird disease caused by ARV and briefly describe its impact on the affected population. (6 points)

Avian reoviruses (ARV) can spread vertically from the mother or horizontally by fecal-oral transmission.  The majority of infections are believed to be caused by fecal-oral transfer, frequently as a result of vertical transmission.  The fecal-oral pathway is how a congenitally contaminated chick distributes the illness across a flock.  Overcrowding, inadequate ventilation, and poor hygiene all contribute to fecal-oral transmission.  Fecal-oral transmission is further supported by the pathogen's resilience and persistence for weeks in the environment or on surfaces.

Commercial and wild hens, ARV results in arthritis and swollen tendons.  Joint swelling and inability to walk are symptoms.  ARV-caused ailments reduce or eliminate the ability for wild bird populations to forage for food or escape from predators.  While illness in commercial chickens can also be fatal due to decisions about treatment costs and product value, predation on sick wild birds is also fatal.


Langya henipavirus (LayV) is an emerging zoonotic virus first identified in China.Describe the likely reservoir and transmission route of Langya virus. Why is LayV classified as a spillover and not a potential EID? (6 points)

Shrews are the reservoir for LayV, because of some surveillance tests of animals in the provinces of Shandong and Henan where cases were reported.  Shrews are common in the rural parts of China, and the majority of the cases involved farmers or frequent wildlife exposure. LayV is spread by direct or indirect contact with shrews and their body fluids. Since LayV has not been shown to spread from person to person, it is not considered an EID. Since the 2018–2022 outbreak, no new cases have been reported. LayV is a spillover because, although it can infect humans in addition to the reservoir animal, the virus has not been shown to be able to survive in other species.



There is a statistical difference between the raccoon roundworm prevalences in the three regions. The prevalence between the central region and the north region (p-value=0.0256) and the central region and the south region (p-value=0.0015) have significant difference, but there is no significant difference between the north and south (p-value=1). The quantity of raccoons and the persistence of raccoon roundworm eggs in the environment may have differences geographically. The central and southern regions might have more or better-established raccoon latrines. There may be geographical variations in raccoon density or in the presence and persistence of raccoon roundworm eggs in the environment.  

There was a significant difference between the prevalence of raccoon roundworm in females compared to males (p-value=0.0087). The prevalence within females was only significant in the south region (p-value=0.0030). There is also a significance between females and males in the central region (p-value=0.0859).  Females having a increased prevalence may suggest social or reproductive behavioral differences that put females in greater contact with contaminated environments or raccoon latrines.  

There was no significant difference in prevalence of raccoon roundworm in adults compared to young adults (p-value=0.2206). There was no significant difference for the prevalence of raccoon roundworm between ages within each region. This poses a need for more research on the differences in environment and population. The southern region has the biggest health risk and environmental risk to people specifically children and domestic animals 

Regions 

Central: 9 /14 infected, prevalence 64.3%, lower 37.1%, upper 84.7% 

North: 14/ 49 infected, prevalence 28.6%, lower 17.0%, upper 42.8% 

South: 27/43 infected, prevalence 62.8%, lower 47.7%, upper 75.9% 

p-value central and north: 0.0256 

p-value central and south: 0.0015 

p-value north and south: 1.0 

p-value regions: 0.0016 

 

Sex 

Female: 24/37 infected, prevalence 64.9%, lower 48.6%, upper 78.6% 

Male: 26/69 infected, prevalence 37.7%, lower 26.7%, upper 50.0% 

p-value sex: 0.0087 

 

Age  

Adult: 36/69 infected, prevalence 52.2%, lower 40.4%, upper 63.8% 

Young Adult: 14/37 infected, prevalence 37.8%, lower 23.4%, upper 54.1% 

p-value age: 0.2206 

 

Sex by Region 

p-value central region, sex: 0.0859; central females 100% prevalence 5/5, central males 44.4% prevalence 4/9 

p-value northern region, sex: 0.2219; northern females 38.1% prevalence 8/21, northern males 21.4% prevalence 6/28 

p-value south region, sex: 0.0030; south females 100% prevalence (11 of 11), south males 50.0% prevalence 16/32

 

Age Class by Region 

p-value central region, age: 1.0; central adults 61.5% prevalence 8/13, central young adults 100% prevalence 1/1 

p-value north region, age: 1.0; north adults 28.0% prevalence 7/25, north young adults 29.2% prevalence 7/24 

p-value south region, age: 0.3126; south adults 67.7% prevalence 21/31, south young adults 50.0% prevalence 6/12 

 

 








